services:
  # DEV
  dev-web-demuxer-arm64:
    container_name: web-demuxer
    image: emscripten/emsdk:3.1.60-arm64
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
  dev-web-demuxer-x86_64:
    container_name: web-demuxer
    image: emscripten/emsdk:3.1.60
    working_dir: /app
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: ["/bin/bash"]